#pragma once
#ifndef RES_ENUM
#define RES_ENUM


enum ResType
{
	RES_NO_RESOURCES = 0,
	RES_ANY_RES = 0,

	RES_STONE = 1,
	RES_IRON = 2,
	RES_COPPER = 3,
	RES_SILICON = 4,
	RES_COAL = 5,
	RES_SULFUR = 6,
	RES_SAND = 7,
	RES_ZINÑ = 8,
	RES_MANGANUM = 9,
	RES_URANIUM = 10,

	RES_GLASS = 101,
	RES_BRASS = 102,
	RES_CONCRETE = 103,
	RES_STEEL = 104,
	RES_HYDROGEN = 105,
	RES_CARBON = 106,
	
	RES_AC_SHELLS = 1001,
	RES_HEAVY_SHELLS = 1002,
	RES_ROCKET = 1003,
	RES_RAIL_SHELLS= 1004
};

#endif RES_ENUM